<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

class Demo extends MAIN_Controller
{

    public function __construct()
    {
        parent::__construct();
        $this->init('demo');
    }

    public function onCommitted($isEnabled)
    {

        if(!defined("DEMO") OR DEMO==false){
            return;
        }

        $script = $this->load->view('demo/script',NULL,TRUE);
        TemplateManager::addScript($script);


    }


    public function onLoad()
   {
       parent::onLoad(); // TODO: Change the autogenerated stub
   }


    public function onInstall()
    {
        return TRUE;
    }

    public function onUpgrade()
    {
        return TRUE;
    }

    public function onEnable()
    {
        return TRUE;
    }


}