<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/**
 * Created by Console.
 * User: Droideve Technology
 * Date: {date}
 * Time: {time}
 */

class Bookmark extends MAIN_Controller {

    private $module = "bookmark";

    public function __construct(){
        parent::__construct();
        $this->init($this->module);

    }

    public function onLoad()
    {

        $this->load->model('bookmark/bookmark_model','mBookmarkModel');
        $this->load->helper('bookmark/bookmark');

    }

    public function onCommitted($isEnabled)
    {

        if($isEnabled){

            $this->register_modules();

        }
    }

    private function register_modules(){

        $this->load->model('bookmark/bookmark_model','mBookmarkModel');
        ActionsManager::register("user","userConnected",function ($user_id){
            $this->mBookmarkModel->updateGuestID($user_id);
        });

        ActionsManager::register("store","storeRemoved",function ($id){

            $this->db->where("module","store");
            $this->db->where("module_id",$id);
            $this->db->delete("bookmarks");

            //remove all linked modules
            $this->db->where('store_id',$id);
            $products = $this->db->get('product');
            $products = $products->result();

            foreach ($products as $product){
                $this->db->where("module","product");
                $this->db->where("module_id",$product->id_product);
                $this->db->delete("bookmarks");
            }

            //remove all linked modules
            $this->db->where('store_id',$id);
            $events = $this->db->get('event');
            $events = $events->result();

            foreach ($events as $event){
                $this->db->where("module","event");
                $this->db->where("module_id",$event->id_event);
                $this->db->delete("bookmarks");
            }

        });

        ActionsManager::register("product","productRemoved",function ($id){
            $this->db->where("module","product");
            $this->db->where("module_id",$id);
            $this->db->delete("bookmarks");
        });
    }

    public function cron(){


    }

    public function onEnable()
    {
        return parent::onEnable(); // TODO: Change the autogenerated stub
    }

    public function onInstall()
    {
        parent::onInstall(); // TODO: Change the autogenerated stub
        $this->mBookmarkModel->createBookmarksTable();


        return TRUE;
    }

    public function onUpgrade()
    {
        parent::onUpgrade(); // TODO: Change the autogenerated stub
        $this->mBookmarkModel->createBookmarksTable();
        $this->mBookmarkModel->update_fields();

        return TRUE;
    }


}

/* End of file UploaderDB.php */