<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

class Nstranslator extends MAIN_Controller
{

    public function __construct()
    {
        parent::__construct();
        $this->init('nstranslator');
    }


    //overrid
    public function onLoad()
    {

        define("TRANSLATOR_MANAGE",'manage');

        $this->load->helper('translate');
        $this->load->helper('translator');

    }

    public function onCommitted($isEnabled)
    {
        if(!$isEnabled)
            return;


        TemplateManager::registerMenuSetting(
            'nstranslator',
            "nstranslator/menu_setting",
            12
        );

        Translate::init();

        CMS_Display::set("language_dropdown_v1","nstranslator/plug/header/list",NULL);

    }

    public function onEnable()
    {
        GroupAccess::registerActions('nstranslator',array(
            TRANSLATOR_MANAGE
        ));
    }

    public function onInstall()
    {
        parent::onInstall(); // TODO: Change the autogenerated stub

        return TRUE;
    }

    public function onUpgrade()
    {
        parent::onUpgrade(); // TODO: Change the autogenerated stub

        GroupAccess::registerActions('nstranslator',array(
            TRANSLATOR_MANAGE
        ));

        return TRUE;
    }

}